branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.13\mingw73_32
  - set QT_TOOLS_DIR=C:\Qt\Tools\mingw730_32\ 
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%
  - qmake -v
  
build_script:
  - qmake Dummy.pro
  - mingw32-make
  
after_build:
  #- windeployqt bin/Dummy.exe
  #- curl https://bintray.com/vszakats/generic/download_file?file_path=openssl-1.1.1c-win32-mingw.zip -o ssl.zip -LO
  #- 7z e ssl.zip
  - dir
  #- mv *.dll bin/
  - mv bin Dummy

#Note: artifacts path should be from root directory
artifacts:
  - path: Dummy
    type: zip
    
deploy: 
  release: dummy-$(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
  auth_token: # your encrypted token from GitHub
    secure: 5c6ifu7R/0JzCAHg9PIxYsWvkc93jD6LZeAUmVoE8TxSMb8953FlsdJwNTzM30XN
  artifact: Dummy.zip 
  force_update: true
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
